apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kirana.name" . }}-config
  labels: {{- include "kirana.labels" . | nindent 4 }}
data:
  {{- range $k, $v := .Values.config }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
  POSTGRES_HOST: {{ include "kirana.name" . }}-postgres
  POSTGRES_DB: {{ .Values.postgres.database | quote }}
  POSTGRES_USER: {{ .Values.postgres.user | quote }}
