apiVersion: v1
kind: Service
metadata:
  name: {{ include "kirana.name" . }}-api
  labels: {{- include "kirana.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  selector: {{- include "kirana.apiSelector" . | nindent 4 }}
  ports:
    - { name: http, port: {{ .Values.service.port }}, targetPort: http }
