apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-canary
spec:
  replicas: 1
  selector:
    matchLabels: { app: checkout, track: canary }
  template:
    metadata:
      labels: { app: checkout, track: canary }
    spec:
      containers:
        - name: app
          image: hashicorp/http-echo:1.0
          args: ["-text=canary v2", "-listen=:5678"]
          ports: [{ containerPort: 5678 }]
          resources: { requests: { cpu: 10m, memory: 16Mi } }
