apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-stable
spec:
  replicas: 9
  selector:
    matchLabels: { app: checkout, track: stable }
  template:
    metadata:
      labels: { app: checkout, track: stable }
    spec:
      containers:
        - name: app
          image: hashicorp/http-echo:1.0
          args: ["-text=stable v1", "-listen=:5678"]
          ports: [{ containerPort: 5678 }]
          resources: { requests: { cpu: 10m, memory: 16Mi } }
